# Generated by Django 4.1.5 on 2023-01-19 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Date', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('By_user', models.TextField()),
                ('chat_count', models.IntegerField()),
                ('Action', models.TextField()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
