# Generated by Django 4.1.5 on 2023-01-20 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Date', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='default/1.png', upload_to='photos/%y/%m/%d')),
                ('location', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField()),
                ('By_user', models.TextField()),
                ('chat_count', models.IntegerField()),
                ('Action', models.TextField()),
                ('type_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Todo.type_item')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
