# Generated by Django 4.1.5 on 2023-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='photo/default/1.png', upload_to='photos/%y/%m/%d'),
        ),
    ]
